ALTER TABLE public.orcamento_planejado 
  DROP COLUMN IF EXISTS valor,
  ADD COLUMN IF NOT EXISTS valor_pgj NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_fmmp NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_fepdc NUMERIC NOT NULL DEFAULT 0;
