-- Script para inserção em lote das Sedes de Promotorias na tabela unidades_requisitantes (PCA 2027)

INSERT INTO public.unidades_requisitantes (nome, tipo, exercicio, ativo) VALUES
('Sede da Promotoria de Justiça de Água Branca', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Amarante', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Avelino Lopes', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Barro Duro', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Batalha', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Beneditinos', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Buriti dos Lopes', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Canto do Buriti', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Capitão de Campos', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Caracol', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Castelo do Piauí', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Cocal', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Cristino Castro', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Demerval Lobão', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Elesbão Veloso', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Fronteiras', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Gilbués', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Guadalupe', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Inhuma', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Itainópolis', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Itaueira', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Jaicós', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Jerumenha', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de José de Freitas', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Luís Correia', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Luzilândia', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Manoel Emídio', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Marcos Parente', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Matias Olímpio', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Miguel Alves', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Monsenhor Gil', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Nossa Senhora dos Remédios', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Padre Marcos', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Parnaguá', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Paulistana', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Pio IX', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Porto', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Regeneração', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de São Pedro do Piauí', 'Sede', 2027, true),
('Sede da Promotoria de Justiça de Simões', 'Sede', 2027, true),
('Sede da Promotoria de Justiça Ribeiro Gonçalves', 'Sede', 2027, true),
('Sede da Promotoria de Justiça São Miguel do Tapuio', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Altos', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Barras', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Bom Jesus', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Campo Maior', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Corrente', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Esperantina', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Floriano', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Oeiras', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Pedro II', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Picos', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Piracuruca', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Piripiri', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de São João do Piauí', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de São Raimundo Nonato', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Simplício Mendes', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Teresina', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de União', 'Sede', 2027, true),
('Sede das Promotorias de Justiça de Valença do Piauí', 'Sede', 2027, true),
('Sede das Promotorias de Justiça Uruçuí', 'Sede', 2027, true);
